# Generated by Django 4.0.2 on 2022-07-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firstview',
        ),
    ]
