# Generated by Django 4.0 on 2022-10-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0002_info_remove_nation_istour_delete_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='raid',
            new_name='value',
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
