# Generated by Django 4.0.2 on 2022-08-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0002_delete_firstview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
