# Generated by Django 4.0.2 on 2022-08-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0003_delete_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xia.player'),
        ),
        migrations.AlterField(
            model_name='minister',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xia.citizen'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_nation', to='xia.nation'),
        ),
    ]
