# Generated by Django 4.0.2 on 2022-08-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0004_alter_citizen_player_alter_minister_citizen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minister',
            name='citizen',
        ),
        migrations.AddField(
            model_name='minister',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xia.player'),
        ),
        migrations.DeleteModel(
            name='Citizen',
        ),
    ]
