# Generated by Django 4.0.2 on 2022-08-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0005_remove_minister_citizen_minister_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='king',
            field=models.CharField(default='', max_length=50),
        ),
    ]
