# Generated by Django 4.1.1 on 2023-04-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("nickname", models.CharField(default="", max_length=50)),
                ("uuid", models.CharField(default="", max_length=50)),
                ("town", models.CharField(default="", max_length=50)),
                ("nation", models.CharField(default="", max_length=50)),
                ("online", models.BooleanField(default=False)),
                ("logintime", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("lastlogin", models.DateField(blank=True, null=True)),
                ("population", models.IntegerField(default=0)),
                ("area", models.IntegerField(default=0)),
                ("x", models.IntegerField(default=0)),
                ("z", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Minister",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="大臣", max_length=20)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orissa.player",
                    ),
                ),
            ],
        ),
    ]
