# Generated by Django 4.0 on 2022-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.CharField(default='', max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('isgpt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('url', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('channel', models.CharField(default='', max_length=50)),
                ('url', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('lyrics', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('ruigo', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('imitate', models.CharField(default='', max_length=1000)),
                ('isjoke', models.BooleanField(default=False)),
                ('isjapanese', models.BooleanField(default=True)),
            ],
        ),
    ]
