# Generated by Django 4.0 on 2026-09-01 14:47

from django.db import migrations, models
from django.db.models import Count
import django.db.migrations.operations.special
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone


# 元は0031_songlink_db / 0037_data_migrate_is_questionable /
# 0038_alter_authoralias_type_choices / 0045_delete_stale_katsuyou_word_rows /
# 0046_ai_unique_janome_lyrics にあったRunPython対象の関数。
# squashmigrationsが自動移植できなかったため手動でコピーしたもの。

def copy_song_to_songs(apps, schema_editor):
    """既存のFK(song)データをM2M(songs)に移行"""
    SongLink = apps.get_model('subekashi', 'SongLink')
    for link in SongLink.objects.filter(song__isnull=False).select_related('song'):
        link.songs.add(link.song)


QUESTIONABLE_SONG_IDS = [6570, 7989, 8000, 8012, 8016]


def set_is_questionable(apps, schema_editor):
    Song = apps.get_model('subekashi', 'Song')
    Song.objects.filter(id__in=QUESTIONABLE_SONG_IDS).update(is_questionable=True)


def unset_is_questionable(apps, schema_editor):
    Song = apps.get_model('subekashi', 'Song')
    Song.objects.filter(id__in=QUESTIONABLE_SONG_IDS).update(is_questionable=False)


def rename_other_to_another(apps, schema_editor):
    AuthorAlias = apps.get_model('subekashi', 'AuthorAlias')
    AuthorAlias.objects.filter(alias_type='other').update(alias_type='another')


def rename_another_to_other(apps, schema_editor):
    AuthorAlias = apps.get_model('subekashi', 'AuthorAlias')
    AuthorAlias.objects.filter(alias_type='another').update(alias_type='other')


# 動詞・形容詞・名詞は実際のトークナイズ結果として katsuyou が常に非空になるため、
# katsuyou="" のまま残っている行は、katsuyou 導入前の word.json を取り込んだ
# 旧データ（新方式では二度と一致しない）とみなせる。
# 副詞・連体詞はもともと katsuyou="" が正当な値のため対象外とする
NON_CONJUGATING_HINSHIS = ("副詞", "連体詞")


def delete_stale_rows(apps, schema_editor):
    Word = apps.get_model('subekashi', 'Word')
    Word.objects.filter(katsuyou="").exclude(hinshi__in=NON_CONJUGATING_HINSHIS).delete()


def delete_duplicate_janome_lyrics(apps, schema_editor):
    # AddConstraint（genetype="janome"のlyricsをユニークにする）を
    # 既存データが妨げないよう、事前に重複を統合する。
    # スコアが最も高い（同点なら先に作られた）1件だけを残し、残りは削除する
    Ai = apps.get_model('subekashi', 'Ai')
    duplicate_lyrics = (
        Ai.objects.filter(genetype='janome')
        .values('lyrics')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
        .values_list('lyrics', flat=True)
    )
    for lyrics in duplicate_lyrics:
        rows = list(Ai.objects.filter(genetype='janome', lyrics=lyrics).order_by('-score', 'id'))
        for row in rows[1:]:
            row.delete()


class Migration(migrations.Migration):

    replaces = [('subekashi', '0001_initial'), ('subekashi', '0002_delete_singleton'), ('subekashi', '0003_song_like_song_views'), ('subekashi', '0004_rename_views_song_view'), ('subekashi', '0005_rename_posttime_song_post_time_and_more'), ('subekashi', '0006_alter_song_like_alter_song_post_time_alter_song_view'), ('subekashi', '0007_contact_alter_song_lyrics'), ('subekashi', '0008_remove_song_isarchived_alter_song_upload_time'), ('subekashi', '0009_article_song_isarrange_song_isdec_song_isnotice_and_more'), ('subekashi', '0010_song_isspetial'), ('subekashi', '0011_song_islock'), ('subekashi', '0012_rename_isspetial_song_isspecial'), ('subekashi', '0013_alter_article_text'), ('subekashi', '0014_alter_song_imitate_alter_song_imitated_and_more'), ('subekashi', '0015_remove_article_id_article_article_id'), ('subekashi', '0016_delete_article'), ('subekashi', '0017_channelalias_channellink_editor_history_songlink_and_more'), ('subekashi', '0018_remove_history_channel_history_edit_type_and_more'), ('subekashi', '0019_rename_edited_time_history_create_time_and_more'), ('subekashi', '0020_remove_song_editor'), ('subekashi', '0021_history_temp_changes'), ('subekashi', '0022_remove_history_changes'), ('subekashi', '0023_rename_temp_changes_history_changes'), ('subekashi', '0022_editor_is_forced_open_editor_is_open'), ('subekashi', '0024_merge_20251119_0931'), ('subekashi', '0025_remove_song_ip'), ('subekashi', '0026_rename_channel_to_author'), ('subekashi', '0027_rename_channel_fields_to_author'), ('subekashi', '0028_song_authors'), ('subekashi', '0029_remove_song_channel'), ('subekashi', '0030_song_islimited'), ('subekashi', '0031_songlink_db'), ('subekashi', '0032_remove_song_url'), ('subekashi', '0033_song_imitates'), ('subekashi', '0034_remove_song_imitate_remove_song_imitated'), ('subekashi', '0035_rename_song_boolean_fields'), ('subekashi', '0036_song_is_questionable'), ('subekashi', '0037_data_migrate_is_questionable'), ('subekashi', '0038_alter_authoralias_type_choices'), ('subekashi', '0039_history_add_author'), ('subekashi', '0040_authoralias_add_group_type'), ('subekashi', '0041_alter_authoralias_name_and_more'), ('subekashi', '0042_word_word_subekashi_w_word_6460af_idx_and_more'), ('subekashi', '0043_word_word_not_equal_candidate'), ('subekashi', '0044_remove_word_unique_word_hinshi_candidate_and_more'), ('subekashi', '0045_delete_stale_katsuyou_word_rows'), ('subekashi', '0046_ai_unique_janome_lyrics'), ('subekashi', '0047_stats_stats_unique_stats_year_month_songrange'), ('subekashi', '0048_alter_author_name_alter_songlink_url')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
                ('view', models.IntegerField(default=0)),
                ('click', models.IntegerField(default=0)),
                ('dup', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('still', '未審査'), ('pass', '公開中'), ('fail', '未通過')], default='still', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lyrics', models.CharField(default='', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('genetype', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=10000)),
                ('post_time', models.DateField()),
                ('answer', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=100, unique=True)),
                ('is_forced_open', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('lyrics', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
                ('isoriginal', models.BooleanField(default=False)),
                ('isjoke', models.BooleanField(default=False)),
                ('isdeleted', models.BooleanField(default=False)),
                ('isdraft', models.BooleanField(default=False)),
                ('isinst', models.BooleanField(default=False)),
                ('issubeana', models.BooleanField(default=True)),
                ('like', models.IntegerField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, null=True)),
                ('isspecial', models.BooleanField(default=False)),
                ('islock', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('song', '曲'), ('arrange', 'アレンジ'), ('otomad', '音MAD'), ('medley', 'メドレー'), ('omnibus', '総集編'), ('notice', '告知'), ('dec', '解読'), ('offv', 'オフボ'), ('cover', 'カバー'), ('joke', 'ネタ動画'), ('other', 'その他')], default='song', max_length=10)),
                ('authors', models.ManyToManyField(blank=True, related_name='songs', to='subekashi.Author')),
                ('islimited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='subekashi.editor')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='subekashi.song')),
                ('history_type', models.CharField(choices=[('new', '新規作成'), ('edit', '編集'), ('delete', '削除申請')], default='new', max_length=10)),
                ('title', models.CharField(default='', max_length=100)),
                ('changes', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('alias_type', models.CharField(choices=[('id', 'ID'), ('abbr', '略称'), ('common', '通称'), ('past', '以前の名称'), ('sns', 'SNSでの名称'), ('spell', '表記揺れ'), ('other', '別名義')], default='other', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='subekashi.author')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='subekashi.author')),
            ],
        ),
        migrations.CreateModel(
            name='SongLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='subekashi.song')),
                ('allow_dup', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('songs', models.ManyToManyField(blank=True, related_name='+', to='subekashi.song')),
            ],
        ),
        migrations.RunPython(
            code=copy_song_to_songs,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='songlink',
            name='song',
        ),
        migrations.AlterField(
            model_name='songlink',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='songlink',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='links', to='subekashi.Song'),
        ),
        migrations.AddField(
            model_name='song',
            name='imitates',
            field=models.ManyToManyField(blank=True, related_name='imitateds', to='subekashi.Song'),
        ),
        migrations.RenameField(
            model_name='song',
            old_name='isoriginal',
            new_name='is_original',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='isjoke',
            new_name='is_joke',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='isdraft',
            new_name='is_draft',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='isinst',
            new_name='is_inst',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='issubeana',
            new_name='is_subeana',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='isspecial',
            new_name='is_special',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='islock',
            new_name='is_lock',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='islimited',
            new_name='is_limited',
        ),
        migrations.AddField(
            model_name='song',
            name='is_questionable',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code=set_is_questionable,
            reverse_code=unset_is_questionable,
        ),
        migrations.AlterField(
            model_name='authoralias',
            name='alias_type',
            field=models.CharField(choices=[('id', 'ID'), ('abbr', '略称'), ('common', '通称'), ('past', '以前の名称'), ('sns', 'SNSでの名称'), ('spell', '表記揺れ'), ('another', '別名義')], default='another', max_length=10),
        ),
        migrations.RunPython(
            code=rename_other_to_another,
            reverse_code=rename_another_to_other,
        ),
        migrations.AddField(
            model_name='history',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='subekashi.author'),
        ),
        migrations.AlterField(
            model_name='authoralias',
            name='alias_type',
            field=models.CharField(choices=[('id', 'ID'), ('abbr', '略称'), ('common', '通称'), ('past', '以前の名称'), ('sns', 'SNSでの名称'), ('spell', '表記揺れ'), ('another', '別名義'), ('group', 'グループ')], default='another', max_length=10),
        ),
        migrations.AlterField(
            model_name='authoralias',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='authoralias',
            constraint=models.UniqueConstraint(condition=models.Q(('alias_type', 'group'), _negated=True), fields=('name',), name='unique_authoralias_name_except_group'),
        ),
        migrations.AddConstraint(
            model_name='authoralias',
            constraint=models.UniqueConstraint(condition=models.Q(('alias_type', 'group')), fields=('name', 'author'), name='unique_authoralias_name_author_for_group'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('hinshi', models.CharField(max_length=20)),
                ('candidate', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word', 'hinshi'], name='subekashi_w_word_6460af_idx'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'hinshi', 'candidate'), name='unique_word_hinshi_candidate'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(check=models.Q(('word', django.db.models.expressions.F('candidate')), _negated=True), name='word_not_equal_candidate'),
        ),
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_word_hinshi_candidate',
        ),
        migrations.AddField(
            model_name='word',
            name='katsuyou',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['hinshi', 'katsuyou'], name='subekashi_w_hinshi_26c9c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'hinshi', 'katsuyou', 'candidate'), name='unique_word_hinshi_candidate'),
        ),
        migrations.RunPython(
            code=delete_stale_rows,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=delete_duplicate_janome_lyrics,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='ai',
            constraint=models.UniqueConstraint(condition=models.Q(('genetype', 'janome')), fields=('lyrics',), name='unique_janome_lyrics'),
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('songrange', models.CharField(choices=[('all', '全て'), ('subeana', 'すべあな界隈曲のみ'), ('xx', 'すべあな界隈曲以外')], default='all', max_length=10)),
                ('song_count', models.IntegerField(default=0)),
                ('total_view', models.IntegerField(default=0)),
                ('total_like', models.IntegerField(default=0)),
                ('total_authors', models.IntegerField(default=0)),
                ('total_imitateds', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['year', 'month', 'songrange'],
            },
        ),
        migrations.AddConstraint(
            model_name='stats',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'songrange'), name='unique_stats_year_month_songrange'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='songlink',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
