# Generated by Django 4.0 on 2023-09-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='isinst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='issubeana',
            field=models.BooleanField(default=True),
        ),
    ]
