# Generated by Django 4.0 on 2022-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.AddField(
            model_name='ai',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ai',
            name='genetype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ai',
            name='similar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='imitated',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
