# Generated by Django 4.0 on 2024-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
                ('view', models.IntegerField(default=1)),
                ('click', models.IntegerField(default=1)),
                ('isdisplay', models.BooleanField(default=False)),
            ],
        ),
    ]
