# Generated by Django 4.0 on 2024-09-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singleton',
        ),
    ]
