# Generated by Django 4.0 on 2023-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='posttime',
            new_name='editedtime',
        ),
        migrations.RemoveField(
            model_name='version',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='version',
            name='imitate',
        ),
        migrations.RemoveField(
            model_name='version',
            name='imitated',
        ),
        migrations.RemoveField(
            model_name='version',
            name='isarchived',
        ),
        migrations.RemoveField(
            model_name='version',
            name='isdeleted',
        ),
        migrations.RemoveField(
            model_name='version',
            name='isdraft',
        ),
        migrations.RemoveField(
            model_name='version',
            name='isinst',
        ),
        migrations.RemoveField(
            model_name='version',
            name='isjoke',
        ),
        migrations.RemoveField(
            model_name='version',
            name='isoriginal',
        ),
        migrations.RemoveField(
            model_name='version',
            name='issubeana',
        ),
        migrations.RemoveField(
            model_name='version',
            name='lyrics',
        ),
        migrations.RemoveField(
            model_name='version',
            name='title',
        ),
        migrations.RemoveField(
            model_name='version',
            name='uploaddata',
        ),
        migrations.RemoveField(
            model_name='version',
            name='url',
        ),
        migrations.AddField(
            model_name='version',
            name='after',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='version',
            name='before',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
