# Generated by Django 4.0 on 2024-02-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0002_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='dup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
