# Generated by Django 4.0 on 2023-09-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0002_song_ip_song_isinst_song_issubeana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='isjapanese',
        ),
        migrations.AddField(
            model_name='song',
            name='isarchived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='isdeleted',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('channel', models.CharField(default='', max_length=500)),
                ('url', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('lyrics', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('imitate', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('imitated', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('posttime', models.DateTimeField(blank=True, null=True)),
                ('uploaddata', models.DateField(blank=True, null=True)),
                ('isoriginal', models.BooleanField(default=False)),
                ('isjoke', models.BooleanField(default=False)),
                ('isdeleted', models.BooleanField(default=True)),
                ('isarchived', models.BooleanField(default=True)),
                ('isdraft', models.BooleanField(default=False)),
                ('isinst', models.BooleanField(default=False)),
                ('issubeana', models.BooleanField(default=True)),
                ('ip', models.CharField(default='', max_length=100)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subekashi.song')),
            ],
        ),
    ]
