# Generated by Django 4.0 on 2022-12-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0002_delete_channel_ai_category_ai_genetype_ai_similar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ai',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ai',
            name='users',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
