# Generated by Django 4.0 on 2022-12-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0003_ai_people_ai_title_ai_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai',
            old_name='points',
            new_name='score',
        ),
    ]
