# Generated by Django 4.0 on 2023-09-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0003_remove_song_isjapanese_song_isarchived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
