# Generated by Django 4.0 on 2024-02-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0003_ad_dup_alter_ad_click_alter_ad_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='isdisplay',
        ),
        migrations.AddField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('still', '未審査'), ('pass', '公開中'), ('fail', '未通過')], default='未審査', max_length=10),
        ),
    ]
