# Generated by Django 4.0 on 2024-09-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0003_song_like_song_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='views',
            new_name='view',
        ),
    ]
