# Generated by Django 4.0 on 2024-09-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0004_rename_views_song_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='posttime',
            new_name='post_time',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='uploaddata',
            new_name='upload_time',
        ),
    ]
