# Generated by Django 4.0 on 2024-10-20 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0005_rename_posttime_song_post_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='view',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
