# Generated by Django 4.0 on 2024-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0006_alter_song_like_alter_song_post_time_alter_song_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(max_length=10000)),
                ('post_time', models.DateField()),
                ('answer', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
