# Generated by Django 4.0 on 2022-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0006_song_isoriginal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='imitate',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
