# Generated by Django 4.0 on 2025-02-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0007_contact_alter_song_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='isarchived',
        ),
        migrations.AlterField(
            model_name='song',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
