# Generated by Django 4.0 on 2025-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0008_remove_song_isarchived_alter_song_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=500)),
                ('tag', models.CharField(choices=[('news', 'ニュース'), ('release', 'リリースノート'), ('howto', '使い方'), ('blog', 'ブログ')], default='', max_length=10)),
                ('text', models.CharField(default='', max_length=500)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_md', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='isarrange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='isdec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='isnotice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='isotomad',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='imitate',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='song',
            name='imitated',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
