# Generated by Django 4.0 on 2022-12-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0008_remove_ai_category_remove_ai_isgpt_remove_ai_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genecategory',
            name='ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subekashi.ai'),
        ),
        migrations.AlterField(
            model_name='genesong',
            name='ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subekashi.ai'),
        ),
    ]
