# Generated by Django 4.0 on 2022-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0009_alter_genecategory_ai_alter_genesong_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='ruigo',
            field=models.CharField(blank=True, default='', max_length=50000, null=True),
        ),
    ]
