# Generated by Django 4.0 on 2025-05-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0009_article_song_isarrange_song_isdec_song_isnotice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isspetial',
            field=models.BooleanField(default=False),
        ),
    ]
