# Generated by Django 4.1.1 on 2023-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subekashi", "0010_alter_song_ruigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(default="", max_length=500),
        ),
    ]
