# Generated by Django 4.0 on 2025-05-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0010_song_isspetial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='islock',
            field=models.BooleanField(default=False),
        ),
    ]
