# Generated by Django 4.0 on 2025-05-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0011_song_islock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='isspetial',
            new_name='isspecial',
        ),
    ]
