# Generated by Django 4.1.1 on 2023-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subekashi", "0011_alter_song_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Singleton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(default="", max_length=100)),
                ("value", models.CharField(default="", max_length=500)),
            ],
        ),
    ]
