# Generated by Django 4.0 on 2025-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0012_rename_isspetial_song_isspecial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
