# Generated by Django 4.1.1 on 2023-05-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subekashi", "0012_singleton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="channel",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="song",
            name="url",
            field=models.CharField(blank=True, default="", max_length=500, null=True),
        ),
    ]
