# Generated by Django 4.1.1 on 2023-06-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subekashi", "0013_alter_song_channel_alter_song_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="song", name="isdraft", field=models.BooleanField(default=False),
        ),
    ]
