# Generated by Django 4.0 on 2025-05-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0013_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='imitate',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='imitated',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
