# Generated by Django 4.1.1 on 2023-06-26 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subekashi", "0014_song_isdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="posttime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 26, 19, 48, 52, 818543)
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="uploaddata",
            field=models.DateField(blank=True, null=True),
        ),
    ]
