# Generated by Django 4.0 on 2025-05-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0014_alter_song_imitate_alter_song_imitated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
