# Generated by Django 4.1.1 on 2023-06-26 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subekashi", "0015_song_posttime_song_uploaddata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="posttime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 26, 19, 49, 15, 124140)
            ),
        ),
    ]
