# Generated by Django 4.0 on 2025-06-03 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0015_remove_article_id_article_article_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
