# Generated by Django 4.0 on 2025-08-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0016_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('alias_type', models.CharField(choices=[('id', 'ID'), ('abbr', '略称'), ('common', '通称'), ('past', '以前の名称'), ('sns', 'SNSでの名称'), ('spell', '表記揺れ'), ('other', '別名義')], default='other', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.CharField(default='', max_length=20000)),
                ('edited_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='ismain',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='isnickname',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='subs',
        ),
        migrations.RemoveField(
            model_name='song',
            name='isarrange',
        ),
        migrations.RemoveField(
            model_name='song',
            name='isdec',
        ),
        migrations.RemoveField(
            model_name='song',
            name='isnotice',
        ),
        migrations.RemoveField(
            model_name='song',
            name='isotomad',
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('song', '曲'), ('arrange', 'アレンジ'), ('otomad', '音MAD'), ('medley', 'メドレー'), ('omnibus', '総集編'), ('notice', '告知'), ('dec', '解読'), ('offv', 'オフボ'), ('cover', 'カバー'), ('joke', 'ネタ動画'), ('other', 'その他')], default='song', max_length=10),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.DeleteModel(
            name='Version',
        ),
        migrations.AddField(
            model_name='songlink',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='subekashi.song'),
        ),
        migrations.AddField(
            model_name='history',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='subekashi.channel'),
        ),
        migrations.AddField(
            model_name='history',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='subekashi.editor'),
        ),
        migrations.AddField(
            model_name='history',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='subekashi.song'),
        ),
        migrations.AddField(
            model_name='channellink',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='subekashi.channel'),
        ),
        migrations.AddField(
            model_name='channelalias',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='subekashi.channel'),
        ),
        migrations.AddField(
            model_name='song',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='subekashi.editor'),
        ),
    ]
