# Generated by Django 4.0 on 2025-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0016_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='imitate',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='song',
            name='imitated',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
