# Generated by Django 4.0 on 2025-08-11 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0017_channelalias_channellink_editor_history_songlink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='channel',
        ),
        migrations.AddField(
            model_name='history',
            name='edit_type',
            field=models.CharField(choices=[('new', '新規作成'), ('edit', '編集'), ('delete', '削除申請')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='edited_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='song',
            name='post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
