# Generated by Django 4.0 on 2025-10-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0018_remove_history_channel_history_edit_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='edited_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='edit_type',
            new_name='history_type',
        ),
        migrations.AlterField(
            model_name='history',
            name='changes',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
