# Generated by Django 4.0 on 2025-10-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0019_rename_edited_time_history_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='editor',
        ),
    ]
