# Generated by Django 4.0 on 2025-11-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0020_remove_song_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='temp_changes',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
