# Generated by Django 4.0 on 2025-11-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0021_history_temp_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='changes',
        ),
    ]
