# Generated by Django 4.0 on 2025-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0021_history_temp_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='is_forced_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editor',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
