# Generated by Django 4.0 on 2025-11-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0022_remove_history_changes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='temp_changes',
            new_name='changes',
        ),
    ]
