# Generated by Django 4.0 on 2025-11-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0022_editor_is_forced_open_editor_is_open'),
        ('subekashi', '0023_rename_temp_changes_history_changes'),
    ]

    operations = [
    ]
