# Generated by Django 4.0 on 2025-11-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0024_merge_20251119_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='ip',
        ),
    ]
