# Generated by Django 4.0 on 2026-01-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0025_remove_song_ip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='ChannelAlias',
            new_name='AuthorAlias',
        ),
        migrations.RenameModel(
            old_name='ChannelLink',
            new_name='AuthorLink',
        ),
    ]
