# Generated by Django 4.0 on 2026-01-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0026_rename_channel_to_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authoralias',
            old_name='channel',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='authorlink',
            old_name='channel',
            new_name='author',
        ),
    ]
