# Generated by Django 4.0 on 2026-01-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0027_rename_channel_fields_to_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='songs', to='subekashi.Author'),
        ),
    ]
