# Generated by Django 4.0 on 2026-01-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0028_song_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='channel',
        ),
    ]
