# Generated by Django 4.0 on 2026-02-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0029_remove_song_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='islimited',
            field=models.BooleanField(default=False),
        ),
    ]
