# Generated by Django 4.0 on 2026-03-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0030_song_islimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlink',
            name='allow_dup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='songlink',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='songlink',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='subekashi.song'),
        ),
        migrations.AlterField(
            model_name='songlink',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
