# Generated by Django 4.0 on 2026-03-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0031_songlink_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
    ]
