# Generated by Django 4.0 on 2026-03-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0031_songlink_allow_dup_songlink_is_removed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlink',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
