# Generated by Django 4.0 on 2026-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0032_remove_song_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='imitates',
            field=models.ManyToManyField(blank=True, related_name='imitateds', to='subekashi.Song'),
        ),
    ]
