# Generated by Django 4.0 on 2026-03-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0033_song_imitates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='imitate',
        ),
        migrations.RemoveField(
            model_name='song',
            name='imitated',
        ),
    ]
