# Generated by Django 4.0 on 2026-08-10 08:50

from django.db import migrations, models


def rename_other_to_another(apps, schema_editor):
    AuthorAlias = apps.get_model('subekashi', 'AuthorAlias')
    AuthorAlias.objects.filter(alias_type='other').update(alias_type='another')


def rename_another_to_other(apps, schema_editor):
    AuthorAlias = apps.get_model('subekashi', 'AuthorAlias')
    AuthorAlias.objects.filter(alias_type='another').update(alias_type='other')


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0037_data_migrate_is_questionable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoralias',
            name='alias_type',
            field=models.CharField(choices=[('id', 'ID'), ('abbr', '略称'), ('common', '通称'), ('past', '以前の名称'), ('sns', 'SNSでの名称'), ('spell', '表記揺れ'), ('another', '別名義')], default='another', max_length=10),
        ),
        migrations.RunPython(rename_other_to_another, rename_another_to_other),
    ]
