# Generated by Django 4.0 on 2026-08-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0038_alter_authoralias_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='subekashi.author'),
        ),
    ]
