# Generated by Django 4.0 on 2026-08-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0039_history_add_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoralias',
            name='alias_type',
            field=models.CharField(choices=[('id', 'ID'), ('abbr', '略称'), ('common', '通称'), ('past', '以前の名称'), ('sns', 'SNSでの名称'), ('spell', '表記揺れ'), ('another', '別名義'), ('group', 'グループ')], default='another', max_length=10),
        ),
    ]
