# Generated by Django 4.0 on 2026-08-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0040_authoralias_add_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoralias',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name='authoralias',
            constraint=models.UniqueConstraint(condition=models.Q(('alias_type', 'group'), _negated=True), fields=('name',), name='unique_authoralias_name_except_group'),
        ),
        migrations.AddConstraint(
            model_name='authoralias',
            constraint=models.UniqueConstraint(condition=models.Q(('alias_type', 'group')), fields=('name', 'author'), name='unique_authoralias_name_author_for_group'),
        ),
    ]
