# Generated by Django 4.0 on 2026-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0041_alter_authoralias_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('hinshi', models.CharField(max_length=20)),
                ('candidate', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['word', 'hinshi'], name='subekashi_w_word_6460af_idx'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'hinshi', 'candidate'), name='unique_word_hinshi_candidate'),
        ),
    ]
