# Generated by Django 4.0 on 2026-08-25 13:34

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0042_word_word_subekashi_w_word_6460af_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(check=models.Q(('word', django.db.models.expressions.F('candidate')), _negated=True), name='word_not_equal_candidate'),
        ),
    ]
