# Generated by Django 4.0 on 2026-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0043_word_word_not_equal_candidate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['hinshi'], name='subekashi_w_hinshi_133f05_idx'),
        ),
    ]
