# Generated by Django 4.0 on 2026-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0044_word_subekashi_w_hinshi_133f05_idx'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_word_hinshi_candidate',
        ),
        migrations.RemoveIndex(
            model_name='word',
            name='subekashi_w_hinshi_133f05_idx',
        ),
        migrations.AddField(
            model_name='word',
            name='katsuyou',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['hinshi', 'katsuyou'], name='subekashi_w_hinshi_26c9c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('word', 'hinshi', 'katsuyou', 'candidate'), name='unique_word_hinshi_candidate'),
        ),
    ]
