# Generated by Django 4.0 on 2026-08-30 06:19

from django.db import migrations, models
from django.db.models import Count


def delete_duplicate_janome_lyrics(apps, schema_editor):
    # 0046のAddConstraint（genetype="janome"のlyricsをユニークにする）を
    # 既存データが妨げないよう、事前に重複を統合する。
    # スコアが最も高い（同点なら先に作られた）1件だけを残し、残りは削除する
    Ai = apps.get_model('subekashi', 'Ai')
    duplicate_lyrics = (
        Ai.objects.filter(genetype='janome')
        .values('lyrics')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
        .values_list('lyrics', flat=True)
    )
    for lyrics in duplicate_lyrics:
        rows = list(Ai.objects.filter(genetype='janome', lyrics=lyrics).order_by('-score', 'id'))
        for row in rows[1:]:
            row.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0045_delete_stale_katsuyou_word_rows'),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_janome_lyrics, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ai',
            constraint=models.UniqueConstraint(condition=models.Q(('genetype', 'janome')), fields=('lyrics',), name='unique_janome_lyrics'),
        ),
    ]
