# Generated by Django 4.0 on 2026-08-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0045_delete_stale_katsuyou_word_rows'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ai',
            constraint=models.UniqueConstraint(condition=models.Q(('genetype', 'janome')), fields=('lyrics',), name='unique_janome_lyrics'),
        ),
    ]
