# Generated by Django 4.0 on 2026-08-30 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0046_ai_unique_janome_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('song_count', models.IntegerField(default=0)),
                ('total_view', models.IntegerField(default=0)),
                ('total_like', models.IntegerField(default=0)),
                ('total_authors', models.IntegerField(default=0)),
                ('total_imitateds', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
        migrations.AddConstraint(
            model_name='stats',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_stats_year_month'),
        ),
    ]
