# Generated by Django 4.0 on 2026-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0047_stats_stats_unique_stats_year_month_songrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='songlink',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
