# Generated by Django 4.0 on 2026-09-05 14:01

from django.db import migrations, models


# #1092: MySQL移行(#593)でDB全体の照合順序をutf8mb4_bin（バイト完全一致）にした結果、
# SQLite本来の一意性判定（バイト完全一致）は再現できたが、副作用としてicontains/iexactに
# よる大文字小文字を区別しない検索が機能しなくなっていた（DjangoのMySQLバックエンドは
# icontains/iexactを列の照合順序に依存する単純なLIKEとして実装しているため）。
#
# 対応として、Author.name・SongLink.urlのunique=Trueを外し、以下の方式でDBレベルの
# 一意性制約を作り直す。
# - SQLite・PostgreSQL: 通常のUNIQUE INDEXを作成する（列の照合順序は元々バイナリ
#   なので、Django標準のunique=Trueと全く同じ挙動になる）
# - MySQL: 検索用に列自体の照合順序を大文字小文字を区別しないutf8mb4_0900_ai_ciに
#   変更した上で、0049と同様の生成列（Generated Column）ワークアラウンドでバイト
#   完全一致用の別列（utf8mb4_bin）を追加し、そちらにUNIQUE INDEXを張る
#
# なお、subekashi_authoralias.nameは既に0049でMySQL側の一意性制約（生成列）が
# 別途あるため、ここでは列自体の照合順序をutf8mb4_0900_ai_ciに変更するのみでよい
# （生成列は追加された時点の照合順序を保持し続けるため、この変更の影響を受けない）

MYSQL_FORWARD_SQL = [
    "ALTER TABLE subekashi_author MODIFY name VARCHAR(255) "
    "CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL",
    "ALTER TABLE subekashi_author ADD COLUMN mysql_unique_author_name VARCHAR(255) "
    "CHARACTER SET utf8mb4 COLLATE utf8mb4_bin GENERATED ALWAYS AS (name) VIRTUAL",
    "ALTER TABLE subekashi_author ADD UNIQUE INDEX mysql_uniq_author_name (mysql_unique_author_name)",
    "ALTER TABLE subekashi_songlink MODIFY url VARCHAR(255) "
    "CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL",
    "ALTER TABLE subekashi_songlink ADD COLUMN mysql_unique_songlink_url VARCHAR(255) "
    "CHARACTER SET utf8mb4 COLLATE utf8mb4_bin GENERATED ALWAYS AS (url) VIRTUAL",
    "ALTER TABLE subekashi_songlink ADD UNIQUE INDEX mysql_uniq_songlink_url (mysql_unique_songlink_url)",
    "ALTER TABLE subekashi_authoralias MODIFY name VARCHAR(500) "
    "CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL",
]

MYSQL_REVERSE_SQL = [
    "ALTER TABLE subekashi_authoralias MODIFY name VARCHAR(500) "
    "CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL",
    "ALTER TABLE subekashi_songlink DROP INDEX mysql_uniq_songlink_url",
    "ALTER TABLE subekashi_songlink DROP COLUMN mysql_unique_songlink_url",
    "ALTER TABLE subekashi_songlink MODIFY url VARCHAR(255) "
    "CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL",
    "ALTER TABLE subekashi_author DROP INDEX mysql_uniq_author_name",
    "ALTER TABLE subekashi_author DROP COLUMN mysql_unique_author_name",
    "ALTER TABLE subekashi_author MODIFY name VARCHAR(255) "
    "CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL",
]


def _drop_unique_indexes(cursor, table, column):
    # AlterFieldでunique=Trueを外した時点でDjango自身が既存のUNIQUE INDEXを
    # 削除している可能性があるため、動的に調べて残っていれば削除する
    # （環境によってDjangoが生成するインデックス名が異なるため、名前は決め打ちしない）
    cursor.execute(
        "SELECT DISTINCT INDEX_NAME FROM information_schema.STATISTICS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s "
        "AND NON_UNIQUE = 0 AND INDEX_NAME != 'PRIMARY'",
        [table, column],
    )
    for (index_name,) in cursor.fetchall():
        cursor.execute(f"ALTER TABLE `{table}` DROP INDEX `{index_name}`")


def add_case_insensitive_search_workaround(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "mysql":
            _drop_unique_indexes(cursor, "subekashi_author", "name")
            _drop_unique_indexes(cursor, "subekashi_songlink", "url")
            for sql in MYSQL_FORWARD_SQL:
                cursor.execute(sql)
        else:
            cursor.execute("CREATE UNIQUE INDEX subekashi_author_name_uniq ON subekashi_author (name)")
            cursor.execute("CREATE UNIQUE INDEX subekashi_songlink_url_uniq ON subekashi_songlink (url)")


def remove_case_insensitive_search_workaround(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "mysql":
            for sql in MYSQL_REVERSE_SQL:
                cursor.execute(sql)
        else:
            cursor.execute("DROP INDEX subekashi_author_name_uniq")
            cursor.execute("DROP INDEX subekashi_songlink_url_uniq")


class Migration(migrations.Migration):

    dependencies = [
        ('subekashi', '0049_mysql_partial_unique_workaround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='songlink',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.RunPython(
            add_case_insensitive_search_workaround,
            remove_case_insensitive_search_workaround,
        ),
    ]
