# Generated by Django 4.0 on 2026-09-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('article', '0001_initial'), ('article', '0002_alter_article_tag'), ('article', '0003_article_author'), ('article', '0004_alter_article_text'), ('article', '0005_alter_article_text'), ('article', '0006_alter_article_tag'), ('article', '0007_article_handle_as_news')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('tag', models.CharField(choices=[('news', 'ニュース'), ('release', 'リリースノート'), ('howto', '使い方'), ('blog', 'ブログ'), ('tool', 'ツール'), ('tech', '技術'), ('other', 'その他')], default='', max_length=10)),
                ('text', models.TextField(blank=True, default='', max_length=1000000, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_md', models.BooleanField(default=True)),
                ('author', models.CharField(default='', max_length=50)),
                ('handle_as_news', models.BooleanField(default=False)),
            ],
        ),
    ]
