# Generated by Django 4.0 on 2025-06-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=500)),
                ('tag', models.CharField(choices=[('news', 'ニュース'), ('release', 'リリースノート'), ('howto', '使い方'), ('blog', 'ブログ'), ('other', 'その他')], default='', max_length=10)),
                ('text', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_md', models.BooleanField(default=True)),
            ],
        ),
    ]
