# Generated by Django 4.0 on 2025-08-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(choices=[('news', 'ニュース'), ('release', 'リリースノート'), ('howto', '使い方'), ('blog', 'ブログ'), ('tool', 'ツール'), ('tech', '技術'), ('other', 'その他')], default='', max_length=10),
        ),
    ]
