# Generated by Django 4.0 on 2026-04-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='handle_as_news',
            field=models.BooleanField(default=False),
        ),
    ]
