# from django.core.management.utils import get_random_secret_key
# get_random_secret_key()

SECRET_KEY = ''

NEW_DISCORD_URL = ''
DELETE_DISCORD_URL = ''
CONTACT_DISCORD_URL = ''
ERROR_DISCORD_URL = ''
DSP_DISCORD_URL = ''

PYTHONANYWHERE_USERNAME = ''
PYTHONANYWHERE_TOKEN = ''

YOUTUBE_API_KEY = ''

DEBUG = True

SEND_DISCORD = False

USE_MYSQL = False
MYSQL_PASSWORD = ""

GOOGLE_DRIVE_CLIENT_ID = ""
GOOGLE_DRIVE_CLIENT_SECRET = ""
GOOGLE_DRIVE_REFRESH_TOKEN = ""
GOOGLE_DRIVE_FOLDER_ID = ""
