from subekashi.views.ad import ad
from subekashi.views.api.ad import AdAPI
from subekashi.views.ad_complete import ad_complete
from subekashi.views.ai import ai
from subekashi.views.ai_result import ai_result
from subekashi.views.api.ai import AiAPI
from subekashi.views.channel import channel
from subekashi.views.contact import contact
from subekashi.views.editor import editor
from subekashi.views.errors import *
from subekashi.views.file import *
from subekashi.views.songs import songs
from subekashi.views.setting import setting
from subekashi.views.song import song
from subekashi.views.song_delete import song_delete
from subekashi.views.song_edit import song_edit
from subekashi.views.song_editor import song_editor
from subekashi.views.song_new import song_new
from subekashi.views.api.song import SongAPI
from subekashi.views.top import top
from subekashi.views.components.song_cards import song_cards
from subekashi.views.components.song_guessers import song_guessers
from subekashi.views.components.toast import toast
