# Generated by Django 4.1.1 on 2023-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(default="", max_length=20)),
                ("nickname", models.CharField(default="", max_length=30)),
                ("comment", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
