# Generated by Django 4.1.1 on 2023-05-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="Users",),
    ]
