# Generated by Django 4.1.1 on 2023-05-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0002_rename_user_users"),
    ]

    operations = [
        migrations.RenameField(model_name="users", old_name="id", new_name="user_id",),
    ]
