# Generated by Django 4.0.2 on 2022-03-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('pv', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Singleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('value', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Siteinfo',
        ),
        migrations.AddField(
            model_name='player',
            name='crime',
            field=models.BooleanField(default=False),
        ),
    ]
