# Generated by Django 4.0.2 on 2022-02-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('player', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
