# Generated by Django 4.0.2 on 2022-03-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0002_analyze_singleton_delete_siteinfo_player_crime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstview',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
