# Generated by Django 4.0.2 on 2022-02-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0002_firstview'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstview',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
