# Generated by Django 4.0.2 on 2022-03-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0004_rename_image_firstview_name_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstview',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
