# Generated by Django 4.0.2 on 2022-02-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0004_firstview_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstview',
            name='display',
        ),
        migrations.RemoveField(
            model_name='firstview',
            name='images',
        ),
        migrations.AddField(
            model_name='firstview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
