# Generated by Django 4.0.2 on 2022-02-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0006_siteinfo_alter_firstview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
