# Generated by Django 4.0.2 on 2022-05-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0006_citizen_nation_remove_firstview_player_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Singleton',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='izuminapp.player'),
        ),
        migrations.AlterField(
            model_name='minister',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='izuminapp.citizen'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='izuminapp.town'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='king',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nation_king', to='izuminapp.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_nation', to='izuminapp.nation'),
        ),
        migrations.AlterField(
            model_name='player',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_town', to='izuminapp.town'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='izuminapp.nation'),
        ),
        migrations.AlterField(
            model_name='town',
            name='mayor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='town_mayor', to='izuminapp.player'),
        ),
    ]
