# Generated by Django 4.0.2 on 2022-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0007_delete_singleton_alter_citizen_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
