# Generated by Django 4.0.2 on 2022-02-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0007_player_primary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oldjson',
        ),
        migrations.AddField(
            model_name='player',
            name='leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='uuid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='nations',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
