# Generated by Django 4.0.2 on 2022-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0009_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='info',
        ),
        migrations.AlterField(
            model_name='nation',
            name='capital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='town',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
