# Generated by Django 4.0.2 on 2022-05-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0010_remove_nation_info_alter_nation_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='istour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='screenshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_screenshot', to='izuminapp.screenshot'),
        ),
    ]
