# Generated by Django 4.0.2 on 2022-05-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0011_nation_istour_tour_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='nickname',
        ),
        migrations.AddField(
            model_name='nation',
            name='moddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='moddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
