# Generated by Django 4.0.2 on 2022-05-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('izuminapp', '0012_remove_nation_nickname_nation_moddate_player_moddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='moddate',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='display',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_tour', to='izuminapp.tour'),
        ),
    ]
