# Generated by Django 4.1.1 on 2022-09-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subeana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='imitate',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='word_song', to='subeana.song'),
        ),
    ]
