# Generated by Django 3.2.7 on 2022-09-13 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subeana', '0002_ai_channel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='isexist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='isexist',
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('words', models.CharField(default='', max_length=10000)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='word_song', to='subeana.song')),
            ],
        ),
    ]
