# Generated by Django 4.0 on 2022-09-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subeana', '0002_alter_song_channel_alter_song_imitate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='ruigo',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
