# Generated by Django 4.0 on 2022-11-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subeana', '0003_word_ruigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ruigo',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
