# Generated by Django 4.0 on 2022-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subeana', '0005_alter_song_lyrics_alter_song_ruigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isjapanese',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='isjoke',
            field=models.BooleanField(default=False),
        ),
    ]
