# Generated by Django 4.0 on 2022-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subeana', '0006_song_isjapanese_song_isjoke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ai',
            name='isgood',
        ),
        migrations.AddField(
            model_name='ai',
            name='bad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ai',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ai',
            name='lyrics',
            field=models.CharField(default='', max_length=100),
        ),
    ]
