# Generated by Django 4.0 on 2022-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniadmc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0, max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
