# Generated by Django 4.0 on 2022-10-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniadmc', '0002_wait_delete_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wait',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
